import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {createApp} from '../server/index.mjs';

test('modern groups expose saved work to teachers and return a quiz without spending a second attempt',async t=>{
 const root=await mkdtemp(join(tmpdir(),'aula-return-'));
 const app=await createApp({dataDir:root,env:{NODE_ENV:'test',AULA_MODEL_V2:'1',ADMIN_DOCUMENT:'99910001',ADMIN_PASSWORD:'Master-Return-2026!'}});
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
 t.after(async()=>{await new Promise(r=>app.server.close(r));assert.ok(resolve(root).startsWith(resolve(tmpdir())+sep+'aula-return-'));await rm(root,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${app.server.address().port}`;
 const client=()=>{let cookie='';return async(path,body,method=body?'POST':'GET',expected=200)=>{const response=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',Origin:base,Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];const data=await response.json();assert.equal(response.status,expected,JSON.stringify(data));return data.data;};};
 const master=client(),student=client(),peer=client();
 await master('/auth/login',{document:'99910001',password:'Master-Return-2026!'});
 const template=await master('/admin/courses',{title:'Plantilla de devoluciones'},'POST',201);
 const group=await master(`/platform/courses/${template.id}/clone`,{kind:'group',title:'Grupo de devoluciones',cohort:'2026-2',code:'R'},'POST',201);
 await master(`/platform/courses/${group.id}/state`,{state:'active'});
 await master(`/admin/courses/${group.id}/enrollments/bulk`,{students:[{document:'99910003',name:'Estudiante de prueba'},{document:'99910004',name:'Compañera de prueba'}]},'POST',201);
 for(const [person,document] of [[student,'99910003'],[peer,'99910004']]){await person('/auth/login',{document,password:document});await person('/auth/first-password',{newPassword:'4567',confirmPassword:'4567'});}
 const question={id:'q1',type:'single',prompt:'Dos más dos',options:['4','5'],correct:[0],points:1};
 const activity=await master(`/academics/courses/${group.id}/activities`,{title:'Cuestionario de prueba',kind:'quiz',status:'published',weight:100,maxAttempts:1,timeLimitMinutes:5,questions:[question]},'POST',201);
 const endpoint=`/academics/activities/${activity.id}`,requestId='modern-return-attempt';
 await student(endpoint);
 let draft=await student(endpoint+'/submit',{requestId,activityRevision:activity.revision,action:'draft',answers:{q1:[1]}},'POST',201);
 assert.equal(draft.state,'draft');
 let teacher=(await master(endpoint+'/submissions')).submissions;
 assert.equal(teacher.length,1);assert.equal(teacher[0].state,'draft');assert.deepEqual(teacher[0].answers,{q1:[1]});
 await peer(`/academics/submissions/${draft.id}/return`,{reason:'Intrusión',version:draft.version},'PATCH',403);
 let sent=await student(endpoint+'/submit',{requestId,activityRevision:activity.revision,version:draft.version,action:'submit',answers:{q1:[1]}},'POST',201);
 assert.equal(sent.attempt,1);
 let graded=await master(`/academics/submissions/${sent.id}/grade`,{points:0.5,feedback:'Revisión personalizada',reason:'Crédito parcial documentado',published:true,version:sent.version},'PATCH');
 assert.equal(graded.points,0.5);
 const due=new Date(Date.now()+3600000).toISOString();
 let returned=await master(`/academics/submissions/${sent.id}/return`,{reason:'Revisa la operación y corrige la respuesta',returnDueAt:due,version:graded.version},'PATCH');
 assert.equal(returned.state,'returned');assert.equal(returned.attempt,1);assert.equal(returned.points,null);
 assert.equal((await student(endpoint)).mine[0].feedback,'Revisa la operación y corrige la respuesta');
 assert.equal((await master(`/academics/courses/${group.id}/gradebook`)).students.find(s=>s.document==='99910003').cells[0].state,'returned');
 assert.equal(app.db.prepare('SELECT count(*) n FROM attempt_starts WHERE activity_id=?').get(activity.id).n,1,'opening the returned quiz restarts its timer');
 await master(`/academics/submissions/${sent.id}/grade`,{points:1,published:true,reason:'No permitido',version:returned.version},'PATCH',400);
 app.db.prepare("UPDATE activities SET config=json_set(config,'$.dueAt',json(?)) WHERE id=?").run(JSON.stringify(new Date(Date.now()-3600000).toISOString()),activity.id);
 draft=await student(endpoint+'/submit',{requestId,activityRevision:activity.revision,version:returned.version,action:'draft',answers:{q1:[0]}},'POST',201);
 assert.equal(draft.id,sent.id);assert.equal(draft.attempt,1);
 const correctionPage=await student(endpoint);
 assert.ok(correctionPage.deadline,'a saved returned draft still has its correction timer after the original deadline');
 const extended=await master(`/academics/submissions/${draft.id}/return`,{reason:'Plazo ampliado para completar la corrección',returnDueAt:new Date(Date.now()+7200000).toISOString(),version:draft.version},'PATCH');
 assert.equal(extended.state,'returned');assert.deepEqual(extended.answers,{q1:[0]});assert.equal(extended.attempt,1);
 await master(`/academics/submissions/${draft.id}/return`,{reason:'Versión desactualizada',version:draft.version},'PATCH',409);
 draft=extended;
 await student(endpoint);
 sent=await student(endpoint+'/submit',{requestId,activityRevision:activity.revision,version:draft.version,action:'submit',answers:{q1:[0]}},'POST',201);
 assert.equal(sent.id,returned.id);assert.equal(sent.attempt,1);assert.equal(sent.returnedAt,null);assert.equal(sent.feedback,'');
 assert.equal(app.db.prepare('SELECT count(*) n FROM submissions WHERE activity_id=?').get(activity.id).n,1);
 assert.equal(app.db.prepare('SELECT count(*) n FROM grade_audit WHERE submission_id=?').get(sent.id).n,3);
});
