import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {createApp} from '../server/index.mjs';

test('modern HTTP flow: administrator creates teacher; scoped groups preserve enrollment and deny foreign access',async t=>{
 const root=await mkdtemp(join(tmpdir(),'aula-platform-'));
 const app=await createApp({dataDir:root,env:{NODE_ENV:'test',AULA_MODEL_V2:'1',ADMIN_DOCUMENT:'99900001',ADMIN_PASSWORD:'Master-Synthetic-2026!'}});
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 t.after(async()=>{await new Promise(r=>app.server.close(r));assert.ok(resolve(root).startsWith(resolve(tmpdir())+sep+'aula-platform-'));await rm(root,{recursive:true,force:true});});
 function client(){let cookie='';return async(path,body,method=body?'POST':'GET',expected=200)=>{const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',Origin:base,Cookie:cookie},body:body?JSON.stringify(body):undefined});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return data.data;};}
 const master=client(),teacher=client(),student=client(),other=client();
 const session=await master('/auth/login',{document:'99900001',password:'Master-Synthetic-2026!'});assert.ok(session.user.roles.includes('master'));
 const tuser=await master('/platform/users',{document:'99900002',name:'Teacher',roles:['teacher']},'POST',201);
 await teacher('/auth/login',{document:'99900002',password:'99900002'});
 await teacher('/auth/first-password',{newPassword:'Teacher-Synthetic-2026!',confirmPassword:'Teacher-Synthetic-2026!'});
 const template=await teacher('/admin/courses',{title:'Template'},'POST',201);assert.equal(template.entityKind,'template');
 const g=await teacher(`/platform/courses/${template.id}/clone`,{kind:'group',title:'Group A',cohort:'2026-2',code:'A'},'POST',201);
 await teacher(`/platform/courses/${g.id}/state`,{state:'active'});
 await teacher(`/admin/courses/${template.id}/enrollments/bulk`,{students:[{document:'99900003',name:'Student'}]},'POST',400);
 const imported=await teacher(`/admin/courses/${g.id}/enrollments/bulk`,{students:[{document:'99900003',name:'Student'}]},'POST',201);assert.equal(imported.summary.enrolled,1);
 const module=await teacher(`/admin/courses/${g.id}/modules`,{title:'Chapter',published:true},'POST',201);
 await teacher(`/admin/modules/${module.id}/resources`,{title:'Material',kind:'html',content:'<p>Lesson</p>',published:true},'POST',201);
 const quiz=await teacher(`/academics/courses/${g.id}/activities`,{title:'Quiz',kind:'quiz',status:'published',weight:100,moduleId:module.id,questions:[{id:'q1',type:'single',prompt:'Two plus two?',options:['4','5'],correct:[0],points:1}]},'POST',201);
 await student('/auth/login',{document:'99900003',password:'99900003'});await student('/auth/first-password',{newPassword:'4567',confirmPassword:'4567'});
 assert.equal((await student('/courses')).length,1);await student('/courses/'+template.id,undefined,'GET',404);
 const sub=await student(`/academics/activities/${quiz.id}/submit`,{requestId:'request-one',action:'submit',activityRevision:1,answers:{q1:[0]}},'POST',201);
 await teacher(`/academics/submissions/${sub.id}/grade`,{points:1,feedback:'Correct',published:true,version:sub.version,reason:'Revisión docente'},'PATCH');
 assert.equal((await teacher(`/academics/courses/${g.id}/gradebook`)).students[0].cells[0].points,1);
 const privateCourse=await master('/admin/courses',{title:'Unassigned'},'POST',201);
 await teacher('/admin/courses/'+privateCourse.id,undefined,'GET',403);
 await teacher('/admin/courses/'+privateCourse.id,{title:'Forbidden'},'PATCH',403);
 await teacher('/platform/users',undefined,'GET',403);
 await master('/platform/users',{document:'99900004',name:'Other',roles:['teacher']},'POST',201);
 await other('/auth/login',{document:'99900004',password:'99900004'});await other('/auth/first-password',{newPassword:'Other-Synthetic-2026!',confirmPassword:'Other-Synthetic-2026!'});
 await other('/academics/activities/'+quiz.id,undefined,'GET',403);
 // Versions retain the denominator used when a historical grade was earned.
 let updated=await teacher('/academics/activities/'+quiz.id,{version:quiz.version,title:'Quiz corrected',changeKind:'editorial'},'PATCH');
 assert.equal((await student('/academics/activities/'+quiz.id)).mine.length,1);
 updated=await teacher('/academics/activities/'+quiz.id,{version:updated.version,changeKind:'evaluated',revisionPolicy:'optional',questions:[{id:'q1',type:'single',prompt:'Two plus two?',options:['4','5'],correct:[0],points:2}]},'PATCH');
 assert.equal((await teacher(`/academics/courses/${g.id}/gradebook`)).students[0].provisional,5);
 const newer=await student(`/academics/activities/${quiz.id}/submit`,{requestId:'request-two',action:'submit',activityRevision:updated.revision,answers:{q1:[1]}},'POST',201);
 await teacher(`/academics/submissions/${newer.id}/grade`,{points:0,feedback:'Review',published:true,version:newer.version,reason:'Revisión de segundo intento'},'PATCH');
 const studentId=(await teacher('/admin/students'))[0].id;
 await teacher('/grade-policy/'+g.id,{activityId:quiz.id,studentId,exempt:true,reason:'Adaptación individual'});
 assert.equal((await teacher(`/academics/courses/${g.id}/gradebook`)).students[0].cells[0].state,'exempt');
 assert.equal((await teacher('/grade-policy/'+g.id)).history.length,2);
 await other('/grade-policy/'+g.id,undefined,'GET',403);
 await teacher('/grade-policy/'+g.id,{activityId:quiz.id,studentId,exempt:false,reason:'Retomar evaluación'});
 const periods=[{id:'p1',title:'Corte único',weight:100}];
 await teacher(`/academics/courses/${g.id}/settings`,{periods,preview:true},'PUT');
 await teacher(`/academics/courses/${g.id}/settings`,{periods,confirmImpact:true},'PUT');
 updated=await teacher('/academics/activities/'+quiz.id,{version:updated.version,periodId:'p1'},'PATCH');
 assert.equal((await teacher(`/academics/courses/${g.id}/gradebook`)).students[0].periods[0].provisional,0);
 const lab=await teacher(`/admin/modules/${module.id}/resources`,{title:'Lab',kind:'lab',content:'<h1>Safe laboratory</h1>',published:true},'POST',201);
 await student('/labs/'+lab.id+'/results',{result:'Observación de laboratorio'});
 assert.equal((await teacher('/labs/'+lab.id+'/results')).length,1);
 await student('/courses/'+g.id);
 const analytics=await teacher('/analytics/'+g.id);assert.equal(analytics.students.length,1);assert.equal(analytics.students[0].pending,0);assert.ok(analytics.students[0].lastGroup);
 await other('/analytics/'+g.id,undefined,'GET',403);
 const entry=await teacher('/library',{kind:'resource',sourceId:lab.id,title:'Reusable lab',shared:true},'POST',201);
 const entries=await teacher('/library');assert.ok(entries.some(x=>x.id===entry.id));
 await teacher('/library/'+entry.id+'/use',{courseId:g.id,moduleId:module.id},'POST',201);
 assert.equal((await teacher('/courses/'+g.id)).modules[0].resources.filter(r=>r.kind==='lab').length,2);
 updated=await teacher('/academics/activities/'+quiz.id,{version:updated.version,title:'Repeat quiz',changeKind:'evaluated',revisionPolicy:'repeat'},'PATCH');
 const repeat=await student('/academics/activities/'+quiz.id);assert.equal(repeat.mine.length,0);assert.equal(repeat.previous.length,2);
 // Recovery closes old credentials, instead of clearing the initial-password gate.
 const recovery=await master('/platform/users/'+tuser.id+'/recover',{});assert.ok(recovery.activationCode);
 await teacher('/auth/login',{document:'99900002',password:'Teacher-Synthetic-2026!'},'POST',401);
 await master('/platform/users/'+tuser.id+'/status',{status:'suspended'});
 await teacher('/admin/courses',undefined,'GET',403);
});
