export function createAnalytics({db,accessModel:a,fail,json,readJson,readSession,requireCourse,audit,academics}){
 const all=(s,...p)=>db.prepare(s).all(...p),one=(s,...p)=>db.prepare(s).get(...p);
 async function handler(req,res,path,method,auth){
  const policy=/^\/api\/grade-policy\/([^/]+)(?:\/([^/]+))?$/.exec(path);
  if(policy){const id=policy[1];a.requireScope(auth,id,'grade');a.group(id);
   if(method==='GET'){json(res,{overrides:all('SELECT * FROM grade_overrides WHERE activity_id IN (SELECT id FROM activities WHERE course_id=?)',id),history:all('SELECT g.*,s.student_id,s.activity_id,u.name FROM grade_audit g JOIN submissions s ON s.id=g.submission_id JOIN users u ON u.id=s.student_id JOIN activities a ON a.id=s.activity_id WHERE a.course_id=? ORDER BY g.id DESC LIMIT 300',id)});return true;}
   if(method==='POST'){const b=await readJson(req);auth=readSession(req);a.requireScope(auth,id,'grade');if(!one('SELECT id FROM activities WHERE id=? AND course_id=?',b.activityId,id)||!one('SELECT id FROM enrollments WHERE course_id=? AND student_id=?',id,b.studentId))fail(400,'Actividad o estudiante fuera del grupo.');if(typeof b.exempt!=='boolean'||typeof b.reason!=='string'||!b.reason.trim()||b.reason.length>1000)fail(400,'Indica un motivo y el estado de exención.');db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO grade_overrides VALUES(?,?,?,?,?,?) ON CONFLICT(activity_id,student_id) DO UPDATE SET exempt=excluded.exempt,reason=excluded.reason,actor_id=excluded.actor_id,created_at=excluded.created_at').run(b.activityId,b.studentId,Number(b.exempt),b.reason.trim(),auth.user.id,new Date().toISOString());audit(auth.user,b.exempt?'grade.exempt':'grade.restore',b.activityId+':'+b.studentId);academics.invalidate(id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}json(res,{success:true});return true;}
  }
  if(path==='/api/platform/overview'&&method==='GET'){
   if(!a.staff(auth)||!a.p.roles(auth.user.id).includes('master'))fail(403,'La vista general requiere perfil máster.');
   json(res,{users:one('SELECT count(*) n FROM users').n,templates:one("SELECT count(*) n FROM courses WHERE entity_kind='template'").n,groups:one("SELECT count(*) n FROM courses WHERE entity_kind='group'").n,enrollments:one("SELECT count(*) n FROM enrollments WHERE status='active'").n,submissions:one('SELECT count(*) n FROM submissions').n,events:all('SELECT action,created_at,target_id FROM audit ORDER BY id DESC LIMIT 100'),permissions:all('SELECT action,target_id,details,created_at FROM permission_audit ORDER BY id DESC LIMIT 100')});return true;
  }
  const m=/^\/api\/analytics\/([^/]+)$/.exec(path);
  if(m&&method==='GET'){
   const id=m[1];a.requireScope(auth,id,'grade');const group=a.group(id),q=new URL(req.url,'http://localhost').searchParams;
   const from=q.get('from')||'0000',to=q.get('to')?q.get('to')+'T23:59:59.999Z':'9999';
   for(const key of ['from','to'])if(q.get(key)&&!/^\d{4}-\d\d-\d\d$/.test(q.get(key)))fail(400,'Fecha de filtro no válida.');if(from>to)fail(400,'Revisa el intervalo de fechas.');
   const cfg=academics.settings(id),activities=academics.list(id).filter(v=>!q.get('activity')||q.get('activity')===v.id),resources=all('SELECT r.id FROM resources r JOIN modules m ON m.id=r.module_id WHERE m.course_id=? AND m.published=1 AND r.published=1',id),students=all('SELECT u.id,u.name,u.document,u.active,e.status,e.starts_at,e.expires_at FROM enrollments e JOIN users u ON u.id=e.student_id WHERE e.course_id=? ORDER BY u.name',id).filter(s=>!q.get('student')||s.id===q.get('student'));
   const now=new Date().toISOString();
   const data=students.map(s=>{
    const progress=all('SELECT p.* FROM progress p JOIN resources r ON r.id=p.resource_id JOIN modules m ON m.id=r.module_id WHERE p.user_id=? AND m.course_id=? AND r.published=1 AND m.published=1',s.id,id);
    const inRange=d=>d&&d>=from&&d<=to,opened=progress.filter(p=>inRange(p.last_opened_at||p.opened_at||p.updated_at)).length,completed=progress.filter(p=>p.completed&&inRange(p.updated_at)).length;
    const submissions=all('SELECT s.*,a.config FROM submissions s JOIN activities a ON a.id=s.activity_id WHERE a.course_id=? AND s.student_id=? AND s.superseded=0',id,s.id).filter(r=>activities.some(a=>a.id===r.activity_id)&&inRange(r.submitted_at||r.updated_at));
    const lastLogin=one("SELECT max(created_at) at FROM audit WHERE actor_id=? AND action LIKE 'auth.login.%'",s.id)?.at||null,lastGroup=one("SELECT max(created_at) at FROM learning_events WHERE user_id=? AND course_id=? AND action='group.enter'",s.id,id)?.at||null;
    const delivered=all("SELECT activity_id FROM submissions WHERE student_id=? AND superseded=0 AND state!='draft'",s.id);const grade=academics.gradeRow(activities.filter(x=>x.status==='published'),s.id,cfg,true),pending=activities.filter(x=>x.status==='published'&&!delivered.some(r=>r.activity_id===x.id)),overdue=pending.filter(x=>x.dueAt&&x.dueAt<now).length;
    return {...s,activeEnrollment:!!s.active&&s.status==='active'&&(!s.starts_at||s.starts_at<=now)&&(!s.expires_at||s.expires_at>now),lastLogin,lastGroup,opened,completed,total:resources.length,progress:resources.length?Math.round(completed/resources.length*100):0,started:submissions.length,submitted:submissions.filter(s=>s.state!=='draft').length,pending:pending.length,overdue,grade,attention:[!lastGroup?'Sin ingreso registrado al grupo':'',overdue?'Actividades vencidas':'',grade.provisional!==null&&grade.provisional<cfg.passMark?'Promedio provisional bajo':''].filter(Boolean)};
   });
   const results=activities.map(activity=>{
    const submissions=all("SELECT * FROM submissions WHERE activity_id=? AND superseded=0 AND state!='draft' ORDER BY attempt DESC",activity.id).filter(s=>(!q.get('student')||s.student_id===q.get('student'))&&s.submitted_at>=from&&s.submitted_at<=to),latest=[...new Map(submissions.map(s=>s.student_id).map(id=>[id,submissions.find(s=>s.student_id===id)])).values()];
    const graded=latest.filter(s=>s.points!==null);
    return {id:activity.id,title:activity.title,submitted:latest.length,average:graded.length?graded.reduce((n,s)=>n+s.points/(JSON.parse(s.payload).previousActivity?.maxPoints||activity.maxPoints)*cfg.scaleMax,0)/graded.length:null,questions:activity.questions.map(question=>{const comparable=latest.filter(s=>s.revision===activity.revision),answered=comparable.filter(s=>Object.hasOwn(JSON.parse(s.payload).answers||{},question.id));return {id:question.id,prompt:question.prompt,answered:answered.length,correct:question.type==='text'?null:answered.filter(s=>JSON.stringify(JSON.parse(s.payload).answers[question.id])===JSON.stringify(question.correct)).length};})};
   });
   const comparable=all("SELECT id,title,cohort,group_code FROM courses WHERE template_id=? AND entity_kind='group'",group.template_id).filter(c=>a.p.can(auth.user.id,c.id,'grade')).map(c=>({...c,enrollments:one('SELECT count(*) n FROM enrollments WHERE course_id=?',c.id).n,activities:one('SELECT count(*) n FROM activities WHERE course_id=?',c.id).n,submissions:one('SELECT count(*) n FROM submissions s JOIN activities a ON a.id=s.activity_id WHERE a.course_id=? AND s.superseded=0',c.id).n}));
   const distribution={progress:[0,0,0,0,0],grades:[0,0,0,0,0],ungraded:0};for(const student of data){distribution.progress[Math.min(4,Math.floor(student.progress/20))]++;if(student.grade.provisional===null)distribution.ungraded++;else distribution.grades[Math.min(4,Math.floor(student.grade.provisional/cfg.scaleMax*5))]++;}const changes=all('SELECT g.created_at,g.before_value,g.after_value,g.reason,s.student_id,a.id activity_id FROM grade_audit g JOIN submissions s ON s.id=g.submission_id JOIN activities a ON a.id=s.activity_id WHERE a.course_id=? AND g.created_at>=? AND g.created_at<=? ORDER BY g.id DESC LIMIT 200',id,from,to).filter(v=>(!q.get('student')||v.student_id===q.get('student'))&&(!q.get('activity')||v.activity_id===q.get('activity')));
   json(res,{distribution,changes,group:{id,title:group.title,cohort:group.cohort,code:group.group_code},settings:cfg,students:data,activities:results,comparison:comparable,events:all('SELECT action,created_at,user_id,object_id FROM learning_events WHERE course_id=? AND created_at>=? AND created_at<=? ORDER BY id DESC LIMIT 200',id,from,to).filter(v=>!q.get('student')||v.user_id===q.get('student')),definitions:{opened:'Abrió el visor del material; no demuestra aprendizaje.',completed:'El estudiante marcó el material como completado.',login:'Último inicio de sesión en la plataforma; no equivale a ingreso al grupo.',group:'Ingreso al grupo registrado desde esta actualización; un valor vacío no prueba que nunca haya accedido antes.',dates:'Los filtros cuentan aperturas por su última fecha y finalizaciones por su última actualización. Las notas y pesos son el estado actual, no una reconstrucción histórica.',questions:'Solo se comparan respuestas de la versión actual de cada cuestionario.',comparison:'Los grupos pueden tener contenidos, evaluaciones y estudiantes diferentes.'}});return true;
  }
  const lab=/^\/api\/labs\/([^/]+)\/results$/.exec(path);
  if(lab){const r=one('SELECT r.*,m.course_id,m.published module_published FROM resources r JOIN modules m ON m.id=r.module_id WHERE r.id=?',lab[1]);if(!r||r.kind!=='lab')fail(404,'Laboratorio no encontrado.');requireCourse(r.course_id,auth);
   if(method==='POST'){const b=await readJson(req);auth=readSession(req);requireCourse(r.course_id,auth);if(auth?.user.role!=='student'||auth.preview||!r.published||!r.module_published)fail(403,'No puedes registrar resultados.');if(typeof b.result!=='string'||!b.result.trim()||b.result.length>10000)fail(400,'Escribe resultados de hasta 10000 caracteres.');db.prepare('INSERT INTO learning_events(user_id,course_id,object_id,action,details,created_at) VALUES(?,?,?,?,?,?)').run(auth.user.id,r.course_id,r.id,'lab.result',JSON.stringify({result:b.result}),new Date().toISOString());audit(auth.user,'lab.result',r.id);json(res,{success:true});return true;}
   if(method==='GET'){const isTeacher=a.staff(auth);if(isTeacher)a.requireScope(auth,r.course_id,'grade');const records=all('SELECT user_id,details,created_at FROM learning_events WHERE object_id=? AND action=? ORDER BY id DESC',r.id,'lab.result').filter(v=>isTeacher||v.user_id===auth.user.id);json(res,records.map(v=>({...v,result:JSON.parse(v.details).result,details:undefined})));return true;}
  }
  return false;
 }
 return {handler};
}
