import {randomUUID} from 'node:crypto';

export function setupChat(db) {
 db.exec(`CREATE TABLE IF NOT EXISTS chat_settings(id INTEGER PRIMARY KEY CHECK(id=1),enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN(0,1)));
 INSERT OR IGNORE INTO chat_settings VALUES(1,1);
 CREATE TABLE IF NOT EXISTS chat_courses(course_id TEXT PRIMARY KEY REFERENCES courses(id) ON DELETE CASCADE,enabled INTEGER NOT NULL DEFAULT 0,student_staff INTEGER NOT NULL DEFAULT 1,student_peers INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS chat_preferences(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,accept_students INTEGER NOT NULL DEFAULT 1);
 CREATE TABLE IF NOT EXISTS chat_conversations(id TEXT PRIMARY KEY,course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,user_a TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,user_b TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TEXT NOT NULL,deleted_at TEXT,deleted_by TEXT REFERENCES users(id) ON DELETE SET NULL,UNIQUE(course_id,user_a,user_b),CHECK(user_a<user_b));
 CREATE TABLE IF NOT EXISTS chat_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,conversation_id TEXT NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,sender_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL,created_at TEXT NOT NULL,edited_at TEXT,deleted_at TEXT,reply_id INTEGER REFERENCES chat_messages(id) ON DELETE SET NULL,client_key TEXT NOT NULL,UNIQUE(conversation_id,sender_id,client_key));
 CREATE INDEX IF NOT EXISTS chat_message_conversation ON chat_messages(conversation_id,id);
 CREATE INDEX IF NOT EXISTS chat_message_sender ON chat_messages(sender_id,created_at);
 CREATE INDEX IF NOT EXISTS chat_conversation_a ON chat_conversations(user_a,course_id);
 CREATE INDEX IF NOT EXISTS chat_conversation_b ON chat_conversations(user_b,course_id);
 CREATE TABLE IF NOT EXISTS chat_members(conversation_id TEXT NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,read_id INTEGER NOT NULL DEFAULT 0,hidden_id INTEGER NOT NULL DEFAULT -1,archived INTEGER NOT NULL DEFAULT 0,muted INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(conversation_id,user_id));
 CREATE TABLE IF NOT EXISTS chat_edits(id INTEGER PRIMARY KEY AUTOINCREMENT,message_id INTEGER NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,body TEXT NOT NULL,changed_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS chat_typing(conversation_id TEXT NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TEXT NOT NULL,PRIMARY KEY(conversation_id,user_id));
 CREATE TABLE IF NOT EXISTS chat_blocks(course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(course_id,user_id));
 CREATE TABLE IF NOT EXISTS chat_reports(id TEXT PRIMARY KEY,message_id INTEGER NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,reporter_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,reason TEXT NOT NULL,created_at TEXT NOT NULL,resolved_at TEXT,UNIQUE(message_id,reporter_id));`);
}

export function createChat({db,accessModel:a,fail,json,readJson,readSession,isEnrolled,audit}) {
 const all=(s,...p)=>db.prepare(s).all(...p),one=(s,...p)=>db.prepare(s).get(...p),run=(s,...p)=>db.prepare(s).run(...p),now=()=>new Date().toISOString();
 const globalOn=()=>!!one('SELECT enabled FROM chat_settings WHERE id=1').enabled;
 const supervisor=(id,c)=>a.p.can(id,c.id,'view');
 const member=(id,c)=>a.p.active(id)&&(supervisor(id,c)||c.lifecycle==='active'&&!!c.published&&isEnrolled(id,c.id));
 const groups=auth=>all("SELECT * FROM courses WHERE entity_kind='group' ORDER BY title,cohort,group_code").filter(c=>member(auth.user.id,c));
 const config=c=>{const s=one('SELECT * FROM chat_courses WHERE course_id=?',c.id);return {id:c.id,title:c.title,code:c.group_code,cohort:c.cohort,enabled:!!s?.enabled,studentStaff:s?!!s.student_staff:true,studentPeers:!!s?.student_peers};};
 const course=(id,auth)=>{const c=a.group(id);if(!member(auth.user.id,c))fail(403,'No tienes acceso al chat de este grupo.');return c;};
 const accepted=id=>one('SELECT accept_students FROM chat_preferences WHERE user_id=?',id)?.accept_students!==0;
 const person=id=>{const u=one('SELECT u.id,u.name,p.photo_version,p.hidden FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.id=?',id);if(!u)return null;const hidden=!!u.hidden&&a.p.staff(id);return {id:u.id,name:u.name,roles:a.p.roles(id),avatarUrl:u.photo_version?`/api/community/avatar/${id}?v=${u.photo_version}`:null,online:!hidden&&!!one('SELECT 1 FROM presence p JOIN sessions s ON s.token_hash=p.session_hash WHERE s.user_id=? AND s.expires_at>? AND p.seen_at>?',id,now(),new Date(Date.now()-90000).toISOString())};};
 function permission(c,from,to){
  const s=config(c),fs=supervisor(from,c),ts=supervisor(to,c);
  if(!globalOn())return 'La mensajería está desactivada por la administración.';
  if(!s.enabled)return 'El chat de este grupo está desactivado.';
  if(!member(from,c)||!member(to,c))return 'Una de las personas ya no tiene acceso activo a este grupo.';
  if(one('SELECT 1 FROM chat_blocks WHERE course_id=? AND user_id=?',c.id,from))return 'El docente ha suspendido tu envío de mensajes en este grupo.';
  if(!fs&&!ts&&!s.studentPeers)return 'El docente no ha habilitado mensajes entre estudiantes.';
  if(!fs&&ts&&(!s.studentStaff||!accepted(to)))return 'Este docente no está recibiendo mensajes de estudiantes.';
  return '';
 }
 function conversation(id,auth){const v=one('SELECT * FROM chat_conversations WHERE id=?',id);if(!v)fail(404,'Conversación no disponible.');const c=course(v.course_id,auth),own=auth.user.id===v.user_a||auth.user.id===v.user_b,monitor=supervisor(auth.user.id,c);if(!own&&!monitor)fail(403,'No puedes acceder a esta conversación.');if(v.deleted_at&&!monitor)fail(404,'La conversación fue retirada por un docente.');return {v,c,own,monitor};}
 function view(v,auth,c){const own=v.user_a===auth.user.id||v.user_b===auth.user.id,other=own?(v.user_a===auth.user.id?v.user_b:v.user_a):null,m=own?one('SELECT * FROM chat_members WHERE conversation_id=? AND user_id=?',v.id,auth.user.id):null,last=one('SELECT * FROM chat_messages WHERE conversation_id=? ORDER BY id DESC LIMIT 1',v.id),unread=own&&!v.deleted_at?one('SELECT count(*) n FROM chat_messages WHERE conversation_id=? AND id>? AND sender_id<>? AND deleted_at IS NULL',v.id,m?.read_id||0,auth.user.id).n:0;return {id:v.id,group:config(c),participants:[person(v.user_a),person(v.user_b)],own,supervised:!own,pendingReports:supervisor(auth.user.id,c)?one('SELECT count(*) n FROM chat_reports r JOIN chat_messages m ON m.id=r.message_id WHERE m.conversation_id=? AND r.resolved_at IS NULL',v.id).n:0,deleted:!!v.deleted_at,archived:!!m?.archived,hidden:!!m&&m.hidden_id>=Number(last?.id||0),muted:!!m?.muted,unread,readId:m?.read_id||0,peerReadId:own?one('SELECT read_id FROM chat_members WHERE conversation_id=? AND user_id=?',v.id,other)?.read_id||0:0,lastId:Number(last?.id||0),lastAt:last?.created_at||v.created_at,preview:last?(last.deleted_at?'Mensaje eliminado':last.body.slice(0,150)):'Sin mensajes',canSend:own&&!v.deleted_at&&!permission(c,auth.user.id,other),reason:!own?'Modo de supervisión: solo lectura.':v.deleted_at?'Conversación retirada.':permission(c,auth.user.id,other),canModerate:supervisor(auth.user.id,c)};}
 function inbox(auth,q){const gs=groups(auth),scope=q.get('group')||'',mode=q.get('mode')||'inbox';if(scope&&!gs.some(c=>c.id===scope))fail(403,'Grupo no disponible.');if(!['inbox','supervision'].includes(mode))fail(400,'Vista de mensajes no válida.');if(mode==='supervision'&&!a.staff(auth))fail(403,'Solo docentes pueden supervisar chats.');const cs=gs.filter(c=>!scope||c.id===scope),result=[];for(const c of cs){const rows=mode==='supervision'&&supervisor(auth.user.id,c)?all('SELECT * FROM chat_conversations WHERE course_id=?',c.id):all('SELECT * FROM chat_conversations WHERE course_id=? AND (user_a=? OR user_b=?)',c.id,auth.user.id,auth.user.id);for(const v of rows){if(v.deleted_at&&!supervisor(auth.user.id,c))continue;result.push(view(v,auth,c));}}result.sort((x,y)=>y.lastAt.localeCompare(x.lastAt));const text=(q.get('search')||'').toLocaleLowerCase('es').slice(0,160),filtered=result.filter(v=>!text||[v.group.title,...v.participants.map(p=>p.name)].join(' ').toLocaleLowerCase('es').includes(text));return {groups:gs.map(c=>({...config(c),canManage:supervisor(auth.user.id,c)})),globalEnabled:globalOn(),canManageGlobal:a.global(auth),canSupervise:a.staff(auth),acceptStudents:accepted(auth.user.id),unread:result.filter(v=>v.own&&!v.hidden&&!v.deleted&&!v.muted).reduce((n,v)=>n+v.unread,0),conversations:filtered.slice(0,300),truncated:filtered.length>300};}
 function messages(ctx,q){const before=q.get('before');if(before&&!/^\d+$/.test(before))fail(400,'Página no válida.');const rows=all(`SELECT * FROM chat_messages WHERE conversation_id=? ${before?'AND id<?':''} ORDER BY id DESC LIMIT 60`,ctx.v.id,...(before?[Number(before)]:[])).reverse();return {...view(ctx.v,ctx.auth,ctx.c),messages:rows.map(m=>({id:m.id,senderId:m.sender_id,body:m.deleted_at?'':m.body,createdAt:m.created_at,editedAt:m.edited_at,deleted:!!m.deleted_at,replyId:m.reply_id,reply:m.reply_id?(()=>{const r=one('SELECT sender_id,body,deleted_at FROM chat_messages WHERE id=? AND conversation_id=?',m.reply_id,ctx.v.id);return r?{senderId:r.sender_id,body:r.deleted_at?'Mensaje eliminado':r.body.slice(0,200)}:null;})():null,...(ctx.monitor?{originalBody:m.deleted_at?m.body:null,history:all('SELECT body,changed_at AS changedAt FROM chat_edits WHERE message_id=? ORDER BY id DESC LIMIT 20',m.id),reports:all('SELECT id,reason,created_at AS createdAt,resolved_at AS resolvedAt FROM chat_reports WHERE message_id=?',m.id)}:{})})),hasOlder:!!rows.length&&!!one('SELECT 1 FROM chat_messages WHERE conversation_id=? AND id<?',ctx.v.id,rows[0].id),typing:all('SELECT user_id FROM chat_typing WHERE conversation_id=? AND user_id<>? AND expires_at>?',ctx.v.id,ctx.auth.user.id,now()).filter(r=>member(r.user_id,ctx.c)&&!one('SELECT 1 FROM profiles WHERE user_id=? AND hidden=1',r.user_id)).map(r=>person(r.user_id))};}
 const bool=(b,k)=>{if(typeof b[k]!=='boolean')fail(400,'Revisa las opciones del chat.');return Number(b[k]);};
 const text=(b,k,max)=>{if(typeof b[k]!=='string'||!b[k].trim()||b[k].trim().length>max)fail(400,`Escribe ${k==='body'?'un mensaje':'un motivo'} de entre 1 y ${max} caracteres.`);return b[k].trim();};
 async function handler(req,res,path,method,auth){
  if(!path.startsWith('/api/chat'))return false;
  if(!auth)fail(401,'Inicia sesión para usar mensajes.');
  if(auth.preview||auth.assurance!=='password')fail(403,'Los mensajes requieren tu sesión personal con contraseña.');
  const q=new URL(req.url,'http://localhost').searchParams,send=(d,s=200)=>{json(res,d,s);return true;};
  const body=async()=>{const b=await readJson(req,24000);const fresh=readSession(req);if(!fresh||fresh.user.id!==auth.user.id||fresh.preview||fresh.assurance!=='password'||fresh.user.must_change_password)fail(401,'La sesión terminó.');const g=/^\/api\/chat\/courses\/([^/]+)/.exec(path),v=/^\/api\/chat\/conversations\/([^/]+)/.exec(path);if(g){const c=course(g[1],fresh);if(method==='PUT'&&!supervisor(fresh.user.id,c))fail(403,'Solo el docente de este grupo puede gestionar su chat.');}if(v){const ctx=conversation(v[1],fresh);if(['remove','restore'].includes(path.split('/').at(-1))&&!supervisor(fresh.user.id,ctx.c))fail(403,'Tus permisos de moderación cambiaron.');if(path.endsWith('/messages')&&ctx.v.deleted_at)fail(403,'La conversación fue retirada.');}return b;};
  if(path==='/api/chat'&&method==='GET')return send(inbox(auth,q));
  if(path==='/api/chat/global'&&method==='PUT'){a.requireGlobal(auth);const b=await body();run('UPDATE chat_settings SET enabled=? WHERE id=1',bool(b,'enabled'));audit(auth.user,'chat.global',null,{enabled:b.enabled});return send({enabled:globalOn()});}
  if(path==='/api/chat/preferences'&&method==='PUT'){if(!a.staff(auth))fail(403,'Esta opción es para docentes.');const b=await body();run('INSERT INTO chat_preferences VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET accept_students=excluded.accept_students',auth.user.id,bool(b,'acceptStudents'));return send({acceptStudents:accepted(auth.user.id)});}
  const setting=/^\/api\/chat\/courses\/([^/]+)$/.exec(path);
  if(setting){const c=course(setting[1],auth);if(method==='GET')return send({...config(c),canManage:supervisor(auth.user.id,c),globalEnabled:globalOn()});if(method==='PUT'){if(!supervisor(auth.user.id,c))fail(403,'Solo el docente de este grupo puede configurar su chat.');const b=await body();run('INSERT INTO chat_courses VALUES(?,?,?,?) ON CONFLICT(course_id) DO UPDATE SET enabled=excluded.enabled,student_staff=excluded.student_staff,student_peers=excluded.student_peers',c.id,bool(b,'enabled'),bool(b,'studentStaff'),bool(b,'studentPeers'));audit(auth.user,'chat.configure',c.id,{courseId:c.id,...b});return send(config(c));}}
  if(path==='/api/chat/contacts'&&method==='GET'){const c=course(q.get('group'),auth),search=(q.get('search')||'').toLocaleLowerCase('es').slice(0,160),users=all("SELECT id FROM users WHERE active=1 AND account_status='active' AND must_change_password=0 AND id<>? ORDER BY name",auth.user.id).filter(u=>member(u.id,c)).map(u=>({...person(u.id),canMessage:!permission(c,auth.user.id,u.id),reason:permission(c,auth.user.id,u.id),blocked:supervisor(auth.user.id,c)&&!!one('SELECT 1 FROM chat_blocks WHERE course_id=? AND user_id=?',c.id,u.id)})).filter(u=>!search||u.name.toLocaleLowerCase('es').includes(search));return send({group:config(c),people:users.slice(0,100),truncated:users.length>100});}
  const block=/^\/api\/chat\/courses\/([^/]+)\/users\/([^/]+)$/.exec(path);
  if(block&&method==='PUT'){const c=course(block[1],auth);if(!supervisor(auth.user.id,c))fail(403,'Solo docentes pueden moderar este grupo.');if(supervisor(block[2],c)||!member(block[2],c))fail(400,'Selecciona un estudiante del grupo.');const b=await body();if(bool(b,'blocked'))run('INSERT OR IGNORE INTO chat_blocks VALUES(?,?)',c.id,block[2]);else run('DELETE FROM chat_blocks WHERE course_id=? AND user_id=?',c.id,block[2]);audit(auth.user,'chat.moderate',block[2],{courseId:c.id,blocked:b.blocked});return send({ok:true});}
  if(path==='/api/chat/conversations'&&method==='POST'){const b=await body(),c=course(b.groupId,auth);if(typeof b.userId!=='string'||b.userId===auth.user.id)fail(400,'Selecciona otra persona.');const reason=permission(c,auth.user.id,b.userId);if(reason)fail(403,reason);const pair=[auth.user.id,b.userId].sort();let v=one('SELECT * FROM chat_conversations WHERE course_id=? AND user_a=? AND user_b=?',c.id,...pair);if(v?.deleted_at)fail(409,'El docente retiró esta conversación. Solicita su restauración.');if(!v){const id=randomUUID();db.exec('BEGIN IMMEDIATE');try{run('INSERT INTO chat_conversations(id,course_id,user_a,user_b,created_at) VALUES(?,?,?,?,?)',id,c.id,...pair,now());for(const user of pair)run('INSERT INTO chat_members(conversation_id,user_id) VALUES(?,?)',id,user);db.exec('COMMIT');v=one('SELECT * FROM chat_conversations WHERE id=?',id);}catch(e){db.exec('ROLLBACK');throw e;}}run('UPDATE chat_members SET hidden_id=-1,archived=0 WHERE conversation_id=? AND user_id=?',v.id,auth.user.id);return send(view(v,auth,c),201);}
  const route=/^\/api\/chat\/conversations\/([^/]+)(?:\/(messages|read|state|typing|remove|restore))?$/.exec(path);
  if(route){const ctx={...conversation(route[1],auth),auth},v=ctx.v,id=v.id,tail=route[2];
   if(!tail&&method==='GET')return send(messages(ctx,q));
   if(tail==='messages'&&method==='POST'){const b=await body();if(!ctx.own||v.deleted_at)fail(403,'Esta conversación es de solo lectura.');const other=v.user_a===auth.user.id?v.user_b:v.user_a,reason=permission(ctx.c,auth.user.id,other);if(reason)fail(403,reason);const content=text(b,'body',5000);if(typeof b.clientKey!=='string'||!/^[\w-]{16,80}$/.test(b.clientKey))fail(400,'Identificador de envío no válido.');const existing=one('SELECT id FROM chat_messages WHERE conversation_id=? AND sender_id=? AND client_key=?',id,auth.user.id,b.clientKey);if(existing)return send({id:existing.id});if(b.replyId!=null&&(!Number.isSafeInteger(b.replyId)||!one('SELECT id FROM chat_messages WHERE id=? AND conversation_id=?',b.replyId,id)))fail(400,'El mensaje citado no pertenece a esta conversación.');if(one('SELECT count(*) n FROM chat_messages WHERE sender_id=? AND created_at>?',auth.user.id,new Date(Date.now()-60000).toISOString()).n>=40)fail(429,'Has enviado muchos mensajes. Espera un minuto.');db.exec('BEGIN IMMEDIATE');let message;try{message=Number(run('INSERT INTO chat_messages(conversation_id,sender_id,body,created_at,reply_id,client_key) VALUES(?,?,?,?,?,?)',id,auth.user.id,content,now(),b.replyId||null,b.clientKey).lastInsertRowid);run('UPDATE chat_members SET archived=0 WHERE conversation_id=?',id);run('UPDATE chat_members SET read_id=? WHERE conversation_id=? AND user_id=?',message,id,auth.user.id);run('DELETE FROM chat_typing WHERE conversation_id=? AND user_id=?',id,auth.user.id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}audit(auth.user,'chat.message.send',String(message),{courseId:ctx.c.id,object:{id,title:'Conversación del grupo',type:'chat'}});return send({id:message},201);}
   if(tail==='read'&&method==='POST'){if(!ctx.own)fail(403,'La supervisión no modifica las confirmaciones de lectura.');const b=await body(),last=one('SELECT COALESCE(MAX(id),0) n FROM chat_messages WHERE conversation_id=?',id).n;if(!Number.isSafeInteger(b.id)||b.id<0||b.id>last)fail(400,'Lectura no válida.');run('UPDATE chat_members SET read_id=MAX(read_id,?) WHERE conversation_id=? AND user_id=?',b.id,id,auth.user.id);return send({ok:true});}
   if(tail==='typing'&&method==='POST'){const b=await body();if(!ctx.own||v.deleted_at||permission(ctx.c,auth.user.id,v.user_a===auth.user.id?v.user_b:v.user_a))fail(403,'No puedes escribir en esta conversación.');if(bool(b,'typing')){run('DELETE FROM chat_typing WHERE expires_at<?',now());run('INSERT INTO chat_typing VALUES(?,?,?) ON CONFLICT(conversation_id,user_id) DO UPDATE SET expires_at=excluded.expires_at',id,auth.user.id,new Date(Date.now()+7000).toISOString());}else run('DELETE FROM chat_typing WHERE conversation_id=? AND user_id=?',id,auth.user.id);return send({ok:true});}
   if(tail==='state'&&method==='PUT'){if(!ctx.own)fail(403,'Solo puedes organizar tus propias conversaciones.');const b=await body();if(b.hidden===true){run('UPDATE chat_members SET hidden_id=(SELECT COALESCE(MAX(id),0) FROM chat_messages WHERE conversation_id=?),read_id=(SELECT COALESCE(MAX(id),0) FROM chat_messages WHERE conversation_id=?) WHERE conversation_id=? AND user_id=?',id,id,id,auth.user.id);}else if(b.hidden===false)run('UPDATE chat_members SET hidden_id=-1 WHERE conversation_id=? AND user_id=?',id,auth.user.id);for(const [key,column] of [['archived','archived'],['muted','muted']])if(b[key]!==undefined)run(`UPDATE chat_members SET ${column}=? WHERE conversation_id=? AND user_id=?`,bool(b,key),id,auth.user.id);return send({ok:true});}
   if(['remove','restore'].includes(tail)&&method==='POST'){if(!ctx.monitor)fail(403,'Solo docentes pueden retirar conversaciones para todos.');const b=await body();if(b.confirm!==id)fail(400,'Confirma la conversación que deseas gestionar.');run('UPDATE chat_conversations SET deleted_at=?,deleted_by=? WHERE id=?',tail==='remove'?now():null,tail==='remove'?auth.user.id:null,id);run('DELETE FROM chat_typing WHERE conversation_id=?',id);audit(auth.user,`chat.${tail}`,id,{courseId:ctx.c.id});return send({ok:true});}
  }
  const messageRoute=/^\/api\/chat\/messages\/(\d+)(?:\/(report))?$/.exec(path);
  if(messageRoute){const m=one('SELECT * FROM chat_messages WHERE id=?',Number(messageRoute[1]));if(!m)fail(404,'Mensaje no disponible.');const ctx=conversation(m.conversation_id,auth);if(messageRoute[2]==='report'&&method==='POST'){if(!ctx.own)fail(403,'Solo participantes pueden reportar un mensaje.');const b=await body();run('INSERT INTO chat_reports VALUES(?,?,?,?,?,NULL) ON CONFLICT(message_id,reporter_id) DO UPDATE SET reason=excluded.reason,resolved_at=NULL',randomUUID(),m.id,auth.user.id,text(b,'reason',1000),now());audit(auth.user,'chat.report',String(m.id),{courseId:ctx.c.id});return send({ok:true});}if(['PATCH','DELETE'].includes(method)){const b=await body();if(ctx.v.deleted_at)fail(403,'La conversación está retirada.');if(m.sender_id!==auth.user.id&&!supervisor(auth.user.id,ctx.c))fail(403,'No puedes modificar mensajes de otra persona.');if(method==='PATCH'){if(m.sender_id!==auth.user.id||m.deleted_at||permission(ctx.c,auth.user.id,ctx.v.user_a===auth.user.id?ctx.v.user_b:ctx.v.user_a))fail(403,'No puedes editar este mensaje.');const content=text(b,'body',5000);db.exec('BEGIN IMMEDIATE');try{run('INSERT INTO chat_edits(message_id,body,changed_at) VALUES(?,?,?)',m.id,m.body,now());run('UPDATE chat_messages SET body=?,edited_at=? WHERE id=?',content,now(),m.id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}else {run('UPDATE chat_messages SET deleted_at=COALESCE(deleted_at,?) WHERE id=?',now(),m.id);audit(auth.user,'chat.message.remove',String(m.id),{courseId:ctx.c.id});}return send({ok:true});}}
  const report=/^\/api\/chat\/reports\/([^/]+)$/.exec(path);
  if(report&&method==='PUT'){const r=one('SELECT r.*,m.conversation_id FROM chat_reports r JOIN chat_messages m ON m.id=r.message_id WHERE r.id=?',report[1]);if(!r)fail(404,'Reporte no disponible.');const ctx=conversation(r.conversation_id,auth);if(!ctx.monitor)fail(403,'Solo docentes pueden resolver reportes.');await body();run('UPDATE chat_reports SET resolved_at=? WHERE id=?',now(),r.id);return send({ok:true});}
  fail(404,'Opción de mensajes no encontrada.');
 }
 return {handler};
}
